### ISSUE TITLE
Ignore folders

### ISSUE THREAD

**Issue by conneroisu** [A-F-V/obsidian-arcana#26]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when I have to turn off arcana to use the latex suite plugin. 
**Describe the solution you'd like**
A ignore fTolder list inside settings to not put the: 
```example
---
arcana: {}
---
```
**Describe alternatives you've considered**
Alternatives to this issue would be manually forking and having my own version or pull request.

**Comment by A-F-V** [comment]
Hi, what version of Arcana are you running? As far as I am aware, this should be gone in the later versions unless there is a bug in the code. 
Did you build from source, or install from Obsidian marketplace?

**Comment by A-F-V** [comment]
Also which arcana tool where you using?

**Comment by conneroisu** [comment]
Installed from marketplace and source. When working on files is adds the aforementioned: 
```markdown
---
arcana: {}
---

```

**Comment by A-F-V** [comment]
Are you using the latest version?
