### ISSUE TITLE
Create option to automatically tag existing files (Darwin)

### ISSUE THREAD

**Issue by dragos240** [A-F-V/obsidian-arcana#30]
**Is your feature request related to a problem? Please describe.**
I don't like needing to use the command prompt to summon Darwin for every file I write, especially if I want to use it to tag existing notes for me

**Describe the solution you'd like**
I would like some way to iteratively tag existing notes. Perhaps specifying a specific folder or a pattern in the title?

**Describe alternatives you've considered**
N/A

**Additional context**
I am using obsidian for journaling/reflection

**Comment by A-F-V** [comment]
Do you mind maybe spelling out some more of the mechanism? For example, if a note already has tags, should it add more? And when should it tag the file? Immediately or maybe after a fixed period?

**Comment by dragos240** [comment]
Sure. I was thinking of an option in the command palette like "Darwin: Tag untagged files". And in the config you could specify the root directory Darwin starts a scan. If a file already has the following snippet, skip this file:

```md
---
tags:
```

I have my journal entries in this hierarchy:
![image](https://github.com/A-F-V/obsidian-arcana/assets/704081/5081273d-9207-477e-a931-a837434a5bbf)

So I would set the root scan folder as `/_2 Journal`

**Comment by A-F-V** [comment]
How about on right clicking a folder in the folder explorer, an option will appear that says `Darwin: Auto tagged all untagged files`?

**Comment by dragos240** [comment]
Sounds good to me

**Comment by dragos240** [comment]
The PR seems to have some issues. When right clicking on a file and `Darwin: Tag file` is selected, I get this error:
![image](https://github.com/A-F-V/obsidian-arcana/assets/704081/4d9ae370-f748-486a-8d97-905f7085b72f)

**Comment by dragos240** [comment]
And once a file is tagged and I use the command palette to select Darwin: tag on an already tagged file, I get this
![image](https://github.com/A-F-V/obsidian-arcana/assets/704081/7bbe0453-204b-449a-9f6c-2130aa76471e).

Seems this happens even if there are no tags

**Comment by A-F-V** [comment]
> The PR seems to have some issues. When right clicking on a file and `Darwin: Tag file` is selected, I get this error:
> 
> ![image](https://github.com/A-F-V/obsidian-arcana/assets/704081/4d9ae370-f748-486a-8d97-905f7085b72f)
> 
> 

This is an outstanding error that happens when langchain calls gpt. There are many possible reasons such as being rate limited etc but I have been unable so far to actually get a useful error message out of it other than this one. Have you checked that you are not over your token limit for month?

**Comment by A-F-V** [comment]
> And once a file is tagged and I use the command palette to select Darwin: tag on an already tagged file, I get this
> 
> ![image](https://github.com/A-F-V/obsidian-arcana/assets/704081/7bbe0453-204b-449a-9f6c-2130aa76471e).
> 
> 
> 
> Seems this happens even if there are no tags
> 
> 

This says that what opens I returned was not usable. I can get it to print out what it returned if that would be useful? 

Also are you using GPT3.5 or 4? Because this is less of a problem on 4 I've found.

**Comment by dragos240** [comment]
> > The PR seems to have some issues. When right clicking on a file and `Darwin: Tag file` is selected, I get this error:
> > ![image](https://user-images.githubusercontent.com/704081/250518354-4d9ae370-f748-486a-8d97-905f7085b72f.png)
> 
> This is an outstanding error that happens when langchain calls gpt. There are many possible reasons such as being rate limited etc but I have been unable so far to actually get a useful error message out of it other than this one. Have you checked that you are not over your token limit for month?

I should check that yeah. I'm using 3.5

**Comment by dragos240** [comment]
@A-F-V Any update?

**Comment by A-F-V** [comment]
There are two parts to this Issue:
1) The error regarding text/event-stream etc.
2) Darwin not being able to get a good list of tags.

The first part needs further investigation. It could be for many reasons, like VPN or OpenAI servers getting overloaded. I just don't know, but its not an exception I generate.

The second part is a problem for weak LLM like GPT3.5 but not 4. It could be that the query I send is too complicated and so if it fails, maybe I will adopt a policy of falling back on a simpler query. I will create a new issue for that.

**Comment by A-F-V** [comment]
https://github.com/A-F-V/obsidian-arcana/issues/51
