### ISSUE TITLE
Add toggle to disable Socrates tab creation on Obsidian start

### ISSUE THREAD

**Issue by dragos240** [A-F-V/obsidian-arcana#38]
**Is your feature request related to a problem? Please describe.**
I do not want to use Socrates, but if I close the tab and reopen Obsidian, it will load again. and obscure my file hierarchy until I close it again.

**Describe the solution you'd like**
I would like a toggle in the plugin settings to either disable Socrates entirely and/or a toggle to prevent it from automatically adding the Socrates tab and navigating away from whatever view (such as file hierarchy) I had open previously.

**Describe alternatives you've considered**
N/A

**Additional context**
None

**Comment by dragos240** [comment]
Not fixed. The update just deselects the "Agent" socrates, but the tab still appears on startup
![image](https://github.com/A-F-V/obsidian-arcana/assets/704081/a2aec59b-0f0a-4d5a-a66c-8a47738bb085)

I'm asking for the brain icon to not spawn each new session

**Comment by A-F-V** [comment]
Understood. This will take longer and I don't think it is on the immediate list of priorities. As far as I can see, being able to disable the view is not common among plugins.

If this gets more push we can reprioritise :).

**Comment by oyes77** [comment]
aditionally:
Add a togleable option to disable any of the plugin "characters" and all their commands/related windows/hotkeys will not appear, that will provide more user customization of what they find or not useful for the plugin, and make slower startup loads even. not just Socrates
