### ISSUE TITLE
QuestionModal reading view as null

### ISSUE THREAD

**Issue by yarub123** [A-F-V/obsidian-arcana#50]
**Describe the bug**
It creates the new file for the flashcards however it doesn't populate them with anything. 

**To Reproduce**
1. Have my shitty laptop
2. Open Obs, call up Feynman, result= ERRORRRRRR

**Expected behavior**
Agatha and Nostradamus and Darwin work. Feynman is trippin on me. Probably because his girl left him for me because my flashcards were cuter.

**Screenshots**
<img width="925" alt="image" src="https://github.com/A-F-V/obsidian-arcana/assets/84487964/fdeb027e-81f0-450f-8f74-cfae6723b2be">

These are more or less 2 renditions of the same/similar errors. I took them over an hour ago so forgot which were pertinent.

<img width="671" alt="image" src="https://github.com/A-F-V/obsidian-arcana/assets/84487964/2410e7d9-01ea-489c-87c2-4210aca51a45">

MacOS 
Obsidian 1.3.5

Context: Jeez FUCK I wasted an unnecessary amount of time playing with this trying to fix it (only 5 fucking hours 🙃). 

Props to the dev(s) this is a monstrosity of code. Maybe not for others, but for me, someone who doesn't know much and never learned it.

Anyways I tried fixing the // src/components/QuestionModal.tsx
in main.js because I believe that was one of the issues... though it proved to not be fruitful. 

The fix has to do with either async as per the error, or the unmount or some shite. Though I would have no clue how to tackle those. I found a few reactDOM codes so I figured fuck it, I'll just post on here 😅

**Comment by A-F-V** [comment]
I think you were onto something with the question modal. I will take a look. Also I will try cleaning up the 'monstrosity' 😉

**Comment by yarub123** [comment]
@A-F-V bahaha I hope I didn't come off as saying that its despicable. The code was beautiful but by monstrosity I just meant that there were so many lines 🙃. 

Do keep in mind I don't code, didn't go to school for it, so it seemed overwhelming compared to the usual css I mess around with for firefox and other little snippets haha. 

As for the question modal this is what I tried yesterday, idk if this was in the right direction: 
```
import React, { useState } from 'react';

function QuestionModalView({ question, onSubmit }) {
  const [result, setResult] = useState('');

  return (
    <div>
      <h1>{question}</h1>
      <div style={{ width: '100%' }}>
        <input
          type="text"
          autoFocus
          onChange={(event) => setResult(event.target.value)}
          onSubmit={() => onSubmit(result)}
          style={{ width: '100%' }}
        />
      </div>
    </div>
  );
}

export default QuestionModalView;


```

**Comment by A-F-V** [comment]
@yarub123 So I think I was using some outdated React calls in the QuestionModal class for onOpen and onClose. I need to make some tweaks to other MRs before I can push this to a new release but should be good to go soon :)

**Comment by yarub123** [comment]
@A-F-V You're a beautiful creature. Take your time, absolutely no rush. Thank you for your prompt responses 🙏

**Comment by yarub123** [comment]
@A-F-V Sorry before you push those merge's I forgot to point out that Socrates doesn't show up at all for me in the command palette. I'm unsure if the two issues are related but wanted to mention that.

**Comment by A-F-V** [comment]
Socrates is not invoked from the command palette but instead is a view in the left window. It's icon looks a little like a brain

**Comment by yarub123** [comment]
@A-F-V right, sorry about that. That was stupid af of me 🤣🤣. Thank you good sir.

**Comment by yarub123** [comment]
@A-F-V Idk whether to start a new issue or not. But the reactDom is fixed 👍. However, I'm getting a similar issue for QuestionModal.eval. Sorry for being the bearer of bad news :/

### Here are the screens:

- **1- Uncaught error. Cannot read properties of null (reading 'view')...** 
- <img width="1068" alt="image" src="https://github.com/A-F-V/obsidian-arcana/assets/84487964/e603bdd0-2e5b-4b43-b788-ceafe3712d59">

- **2- Expanded:**
- <img width="1067" alt="image" src="https://github.com/A-F-V/obsidian-arcana/assets/84487964/20055fe1-b9b0-422c-8301-f9b3e906943e">

- **3- Scrolling *plugin:arcana:51655* in view**
- <img width="702" alt="image" src="https://github.com/A-F-V/obsidian-arcana/assets/84487964/542492ca-7bbf-49b0-aa55-74bf6fd8b916">

- **4- Above, expanded:**
- <img width="1009" alt="image" src="https://github.com/A-F-V/obsidian-arcana/assets/84487964/858d4825-ba39-4f03-aca6-c15a3ac8107d">

Thank you for your help btw. Appreciate your recent update 🙏

**Comment by yarub123** [comment]
@A-F-V Hmm idk what's going on. Here are some images from another test run today. 

1. Yes it creates a new editor with the naming convention: "Flashcard - testfeyn" in the FeynmanFlashcards folder in root
2. File name: testfeyn
3. All the other functions of Arcana function perfectly for me, idk why this one is giving me issues. 
4. Yup, just the regular console (⌘⇧I) 

Today's images: first one are a few errors I noticed on startup today, maybe it has to do with that? second image is same error as before: 
1- 
<img width="680" alt="image" src="https://github.com/A-F-V/obsidian-arcana/assets/84487964/6e01f4a6-dd03-4923-8edb-14ee570dfe14">

2- 
<img width="669" alt="image" src="https://github.com/A-F-V/obsidian-arcana/assets/84487964/7aec70fd-b1e0-4379-9f7c-ba2a411bb92a">

Thank you for reaching out

**Comment by yarub123** [comment]
Update: I disabled all plugins and started from scratch. It works. I guess one of these bastard plugins was interfering with it. Fucking weird. Oh well. Sorry about stressing you out like that lool. That was fucked up of me. @A-F-V

**Comment by A-F-V** [comment]
No worries at all. Glad it's working now
