### ISSUE TITLE
 Customised conversation agent

### ISSUE THREAD

**Issue by kmaustral** [A-F-V/obsidian-arcana#57]
I've followed the instructions, but I cannot Aristotle to function. I made a file as you specified and added it to a folder that is correctly entered in the options. But I can't find a way of activating it. Should an active conversation agent come up in the Command Palette?

**Comment by A-F-V** [comment]
If you go to where you access Socrates, which is in the left view, you will see an option for your agent (in addition to Socrates)

**Comment by kmaustral** [comment]
Got it. Thanks.

**Comment by kmaustral** [comment]
When you click "Send note", does it send the Obsidian note in the main window?

**Comment by A-F-V** [comment]
It sends the currently active note you are writing in, and there is a button for copying a message from the AI into your current note. 

Interestingly, if you are using Canvas, it can sends the contents of the entire canvas which is pretty cool (and not really explicitly programmed for)

You can always test this by writing something in a note, sending to your agent and asking them about what was in that note.

**Comment by A-F-V** [comment]
@kmaustral Good to close?

**Comment by kmaustral** [comment]
Thank you!
