### ISSUE TITLE
Charles Darwin Tag selector feature

### ISSUE THREAD

**Issue by oyes77** [A-F-V/obsidian-arcana#60]
**Is your feature request related to a problem? Please describe.**
In my and i'm sure other people's obsidian there are Tags for different purposes, like dataview organizing, daily notes, etc, that doesn't want to be messed up or used where they don't belong.

**Describe the solution you'd like**
An option in settings to make Charles Darwin only use a subset of tags/Ignore a set of tags, ex:

Don't use:
NoteType/daily
NoteType/Weekly
NoteType/Monthly

Option for Regex, or StartWith, which could be helpful in this case of sub tags, if startwith Notetype then ignore
 
**Describe alternatives you've considered**

**Additional context**

**Comment by A-F-V** [comment]
This seems very reasonable and straightforward. Let me schedule this in.

**Comment by oyes77** [comment]
> This seems very reasonable and straightforward. Let me schedule this in.

Just thought of a nice addition to solidify things up, make Darwin not use flashcards tags by default, unless it's in the flashcards folder (?, then inverse, only use flashcard tags existent or not.

**Comment by A-F-V** [comment]
Exclude tag list in settings which support wild cards added
