### ISSUE TITLE
Metadata summary

### ISSUE THREAD

**Issue by oyes77** [A-F-V/obsidian-arcana#61]
**Is your feature request related to a problem? Please describe.**
Some people like to have a summary field in their metadata for dataview queries, I personally don't do that, but i've seen cases and thought this could be interesting.
**Describe the solution you'd like**
A metadata summary of the note in only a few lines, if you want to expand this feature, i'd find it more useful to get metadata fields from the note (ex: you set it up to get how many times you ate from a daily note log and put it in the specified Food field.
**Describe alternatives you've considered**
There are plugins like inline fields and solutions that doesn't need AI, or just do it manually I suppose, but this would allow a lot more flexibility in just writing something and let AI make the "database" part.

**Comment by A-F-V** [comment]
Could you elaborate with more examples?

**Comment by oyes77** [comment]
sure, here's an example of a note, It's in spanish, but just for the sake of the example isn't really relevant:

```
# Ejercicio De Ads

## Facebook
Hacer un ad con estas estrategias para facebook.

### 1-Engage Time:
mide el tiempo que los usuarios pasan interactuando con una publicación. Cuanto más tiempo pasen los usuarios interactuando con una publicación, mayor será la puntuación de Engage Time.

### 2-Relevance Score:
determina la relevancia de una publicación para el público objetivo. El Relevance Score se basa en factores como la calidad del contenido, el nivel de interacción y el tipo de publicación.

### 3-Personalización:
El algoritmo de Facebook también se personaliza para cada usuario individual. Facebook utiliza información sobre los intereses, la ubicación y el historial de interacción de cada usuario para determinar qué publicaciones son más relevantes para ellos.

### 4-Recency:
La frescura de una publicación también es importante para el algoritmo de Facebook. Las publicaciones más recientes suelen tener una mayor visibilidad en la red social.

### 5-Tipo De Contenido:
El algoritmo de Facebook también prioriza ciertos tipos de contenido, como videos, imágenes y publicaciones con enlaces.
```

a summary example would be like this, I used the following chatGPT prompt:
Explain shortly an concisely what following text is about in only one short paragraph, it must give me an idea of what this text is about at a glance and must be not more than 300-400 characters long. Use specific wording if needed.

```
---
Summary: This text is about strategies for advertising on Facebook. It covers five key factors: Engage Time, Relevance Score, Personalization, Recency, and Content Type. These factors influence how successful your posts are on Facebook, helping you engage with your target audience effectively.
---
```

Then the summary metadata can be shown in dataview, like a file description, if you may.
You could also implement this by making Socrates send an answer or part of an answer to a metadata field, but i'd prefer for it to be it's own thing!

**Comment by oyes77** [comment]
And about the metadata from the text, there's another example, Which I generated:

```
## Diary Entry - A Day in the Life of Ezma 📖

**Morning**

- *8:00 AM:* Woke up feeling refreshed.
- *8:30 AM:* Enjoyed a delicious breakfast of avocado toast and a cup of coffee.
- *9:00 AM:* Started the day with some painting, working on a new canvas inspired by nature.

**Afternoon**

- *12:30 PM:* Took a break for lunch, had a healthy salad with grilled chicken.
- *1:30 PM:* Went for a relaxing photography session in the park, capturing the beauty of flowers and landscapes.
- *3:00 PM:* Decided to write a short story, got lost in the world of words and creativity.

**Evening**

- *6:00 PM:* Prepared a scrumptious dinner of spaghetti aglio e olio.
- *7:30 PM:* Continued working on my coding project in Python, experimenting with new ideas.
- *9:00 PM:* Wrapped up the day with some cozy music, recording the mesmerizing sunset.

**Night**

- *10:30 PM:* Took a soothing bath to unwind and relax.
- *11:00 PM:* Read a good book, drifting into the world of imagination.

What a fulfilling day it has been! 😊
```

This is focused into a Journal since this would be my personal Use case, but you could make it work with other stuff and properties to fill, so:

The AI would get the note and a predefined set of metadata based on folders, templates, the fields that are already in the note or something so it doesn't just makes up things, similar to what I suggested with the Darwin tags, and then fills them up based on the note

```go
---
Meals: 3
Activities: Read, Code, Photography, art, writing
//alternatively//
Read: true
Code: true
Photography: true
Art: true
Exercise: false
Writing: true
School: false
Weight: //Left empty since there was no data, or don't bring//
---
```

**Comment by A-F-V** [comment]
@oyes77 This is quite advanced but here are my ideas are the following:
- This will be a new character (called plugins). Any people you want it to be named after?
- The user can point Arcana to a folder of meta data templates
- Then invoking this new character on a note will give you a drop down of these templates. Once you select one, it will apply that template to the note, updating if it was already invoked.

The hard bit is what the template looks like. I am thinking that the user creates headers for all the meta data fields and then the body of that section is the prompt sent.

Thoughts?

**Comment by guix54** [comment]
If you can create tags with Darwin, I suppose it will be possible to insert the result of the prompt in another field of the property

**Comment by A-F-V** [comment]
Yes exactly, but just note that it would duplicate the result.

for example, you could make a template like this:
```
# keywords
Copy all tags (text starting with a hash) from this document and from the front matter (the space seperated list).
```

**Comment by A-F-V** [comment]
https://github.com/A-F-V/obsidian-arcana#ford

**Comment by guix54** [comment]
perfect!
