### ISSUE TITLE
Define other properties type  for Darwin

### ISSUE THREAD

**Issue by guix54** [A-F-V/obsidian-arcana#66]
**Describe the solution you'd like**
in option, instead of using tags field, specify another type like highlight, keyword..
**Describe alternatives you've considered**
copy created tags into other property :-(
**Additional context**

**Comment by A-F-V** [comment]
I don;t think this is even really possible as Obsidian uses the tags property for its tagging tab.
However, this may be of interest to you: https://github.com/A-F-V/obsidian-arcana/issues/61
