### ISSUE TITLE
Failed to install plugin

### ISSUE THREAD

**Issue by joanofarcana** [A-F-V/obsidian-arcana#97]
I'm unable to install Arcana from the Obsidian application, but I can install other plugins. I've started the application with Administrative privileges, toggled Restrictive mode, and created a fresh vault. I've included screenshots of the error message, Arcana version (as reported by Obsidian), and developer console error.
Am I missing something? Is there anything else I can try?

![image](https://github.com/A-F-V/obsidian-arcana/assets/6021893/01d178d5-d605-4121-9c35-62e044fc2f95)

![image](https://github.com/A-F-V/obsidian-arcana/assets/6021893/1f2a52aa-5201-48da-a169-a01ea196cc62)

**Comment by A-F-V** [comment]
Fixed, thanks for brining to my attention. 
Issue was that CICD marks new build versions as "Draft" so the latest version wasn't technically available yet, hence why it was probably a 404

**Comment by joanofarcana** [comment]
Working on my end now. Thanks for the quick fix!
